/**
 * The authored content, statically imported and handed to the core.
 *
 * `docs/field-framework/ARCHITECTURE.md` (Authored content) locks the layout
 * and the rule: all gameplay data is versioned JSON under `field_game/content/`,
 * statically imported into the worker bundle at build time and never fetched at
 * runtime, and `content_hash` is the SHA-256 over the concatenation of the
 * manifest bytes and every listed file's bytes in manifest order, computed by
 * the build and embedded.
 *
 * Each file is imported as its bytes rather than as parsed data, because the
 * bytes are what the hash is over: the core recomputes the digest across
 * exactly what it is handed and refuses the bundle when it disagrees with the
 * one the build embedded. That is what keeps a stale generated digest from
 * shipping quietly, and it is why nothing here re-serializes anything.
 *
 * The order the files are handed over in is the manifest's own — chapters, then
 * Forms, then pressures, each in its listed order — and it is taken from the
 * manifest at load rather than from the order of the imports below, so the two
 * cannot drift apart.
 *
 * `../build/content.json` is generated by `tools/content-build.mjs`, which the
 * build and the test setup both run.
 */

import generated from '../build/content.json';

import manifestText from '../../content/manifest.json?raw';

import thePull from '../../content/chapters/the_pull.json?raw';
import theEdge from '../../content/chapters/the_edge.json?raw';
import theLoop from '../../content/chapters/the_loop.json?raw';
import theEcho from '../../content/chapters/the_echo.json?raw';
import theMesh from '../../content/chapters/the_mesh.json?raw';
import theBreak from '../../content/chapters/the_break.json?raw';
import theRewrite from '../../content/chapters/the_rewrite.json?raw';
import theQuietEdge from '../../content/chapters/the_quiet_edge.json?raw';

import thread from '../../content/forms/thread.json?raw';
import drain from '../../content/pressures/drain.json?raw';
import noise from '../../content/pressures/noise.json?raw';
import fracture from '../../content/pressures/fracture.json?raw';
import flood from '../../content/pressures/flood.json?raw';
import interference from '../../content/pressures/interference.json?raw';
import drift from '../../content/pressures/drift.json?raw';
import ring from '../../content/forms/ring.json?raw';
import relay from '../../content/forms/relay.json?raw';
import vault from '../../content/forms/vault.json?raw';
import lens from '../../content/forms/lens.json?raw';
import knot from '../../content/forms/knot.json?raw';
import wake from '../../content/forms/wake.json?raw';
import chorus from '../../content/forms/chorus.json?raw';

/** The bundle the core is opened with. */
export interface ContentBundle {
  /** The digest the build computed and embedded. */
  hash: string;
  /** The manifest, as its own bytes. */
  manifest: string;
  /** Every listed file's bytes, in manifest order. */
  files: string[];
}

/** The manifest's shape, as this module reads it. */
interface Manifest {
  content_version: number;
  chapters: string[];
  forms: string[];
  pressures: string[];
}

/** The eight chapters, in the closed set's own order. */
const CHAPTERS: Record<string, string> = {
  the_pull: thePull,
  the_edge: theEdge,
  the_loop: theLoop,
  the_echo: theEcho,
  the_mesh: theMesh,
  the_break: theBreak,
  the_rewrite: theRewrite,
  the_quiet_edge: theQuietEdge,
};

const FORMS: Record<string, string> = {
  thread,
  ring,
  relay,
  vault,
  lens,
  knot,
  wake,
  chorus,
};

/** The six authored pressures, in the closed set's own order. */
const PRESSURES: Record<string, string> = {
  drain,
  noise,
  fracture,
  flood,
  interference,
  drift,
};

/** The manifest text exactly as it sits on disk, which is what is hashed. */
export const MANIFEST_TEXT = manifestText;

/** The digest the build embedded. */
export const CONTENT_HASH: string = generated.content_hash;

/**
 * The bundle, in manifest order. A manifest naming a file this build does not
 * carry is a defect in the build rather than a fault the core can answer, so it
 * throws here: the worker's fault path turns it into the one error envelope.
 */
export function contentBundle(): ContentBundle {
  const manifest = JSON.parse(manifestText) as Manifest;
  const listed: [string[], Record<string, string>][] = [
    [manifest.chapters, CHAPTERS],
    [manifest.forms, FORMS],
    [manifest.pressures, PRESSURES],
  ];
  const files: string[] = [];
  for (const [ids, held] of listed) {
    for (const id of ids) {
      const text = held[id];
      if (text === undefined) {
        throw new Error(`field_game content: the manifest lists ${id}, which is not bundled`);
      }
      files.push(text);
    }
  }
  return { hash: CONTENT_HASH, manifest: manifestText, files };
}
