// The content build: the manifest, the digest rule, and the generated file the
// worker imports.
//
// Dependency-free, like every other check under `tools/`: node built-ins only.

import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

import {
  CONTENT_DIR,
  GENERATED_RELATIVE,
  MANIFEST_RELATIVE,
  MIN_CURRENT_WIDTH_UNITS,
  contentFiles,
  contentHash,
  geometry,
} from './content-build.mjs';

const TOOLS_DIR = path.dirname(fileURLToPath(import.meta.url));
const WORKSPACE = path.resolve(TOOLS_DIR, '..');

/**
 * A workspace of its own, holding a copy of the authored content, for a test
 * that needs content the real workspace does not have. The real content is
 * never edited: a test that mutated it would leave the workspace changed
 * behind it, and every later test would be reading whatever it left.
 */
function scratch(edit = () => {}) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'field-game-content-'));
  fs.cpSync(path.join(WORKSPACE, CONTENT_DIR), path.join(root, CONTENT_DIR), {
    recursive: true,
  });
  edit({
    root,
    read: (relative) => fs.readFileSync(path.join(root, relative), 'utf8'),
    write: (relative, text) => {
      fs.mkdirSync(path.dirname(path.join(root, relative)), { recursive: true });
      fs.writeFileSync(path.join(root, relative), text);
    },
    remove: (relative) => fs.rmSync(path.join(root, relative)),
  });
  return root;
}

test('the manifest lists files that exist, with machine ids', () => {
  const { manifest, files } = contentFiles(WORKSPACE);
  assert.equal(manifest.content_version, 2);
  assert.ok(Array.isArray(manifest.chapters) && manifest.chapters.length > 0);
  assert.deepEqual(
    manifest.pressures,
    ['drain', 'noise', 'fracture', 'flood', 'interference', 'drift'],
    'the six pressures, in the closed set\'s own order',
  );
  for (const file of files) {
    assert.ok(fs.existsSync(path.join(WORKSPACE, file.relative)), file.relative);
    assert.match(file.id, /^[a-z][a-z0-9_]*$/);
  }
  // Chapters first, then Forms, then pressures: the order the concatenation
  // reads, which is the manifest's own list order.
  const kinds = files.map((file) => file.kind);
  const rank = { chapters: 0, forms: 1, pressures: 2 };
  assert.deepEqual(kinds, [...kinds].sort((a, b) => rank[a] - rank[b]));
});

test('the hash is the digest over the manifest and every listed file, in order', () => {
  const { manifestBytes, files } = contentFiles(WORKSPACE);
  const digest = crypto.createHash('sha256');
  digest.update(manifestBytes);
  for (const file of files) digest.update(file.bytes);
  assert.equal(contentHash(WORKSPACE), digest.digest('hex'));
  assert.match(contentHash(WORKSPACE), /^[0-9a-f]{64}$/);
});

test('the order the files are hashed in is the manifest order, not the disk order', () => {
  // Reversing the manifest's own list must move the digest, which is what makes
  // "in manifest order" a rule rather than a coincidence.
  const { manifestBytes, files } = contentFiles(WORKSPACE);
  const forward = crypto.createHash('sha256');
  forward.update(manifestBytes);
  for (const file of files) forward.update(file.bytes);
  const backward = crypto.createHash('sha256');
  backward.update(manifestBytes);
  for (const file of [...files].reverse()) backward.update(file.bytes);
  assert.notEqual(forward.digest('hex'), backward.digest('hex'));
});

test('the generated file the worker imports is current', () => {
  // The build writes it and the worker imports it; the core recomputes the
  // digest over the bytes it is handed and refuses a stale one. This is the
  // same check without opening a core.
  const generated = path.join(WORKSPACE, GENERATED_RELATIVE);
  assert.ok(fs.existsSync(generated), `${GENERATED_RELATIVE} is generated by the build`);
  const held = JSON.parse(fs.readFileSync(generated, 'utf8'));
  assert.equal(held.content_hash, contentHash(WORKSPACE));
  assert.equal(held.content_version, 2);
  // The directory keeps itself out of history, the way the generated module
  // directory does.
  const ignore = path.join(path.dirname(generated), '.gitignore');
  assert.equal(fs.readFileSync(ignore, 'utf8').trim(), '*');
});

test('every authored file is integers only, as canonical JSON requires', () => {
  const { files, manifestRelative } = contentFiles(WORKSPACE);
  const paths = [manifestRelative, ...files.map((file) => file.relative)];
  for (const relative of paths) {
    const text = fs.readFileSync(path.join(WORKSPACE, relative), 'utf8');
    // Numbers in content files are integers only: no fraction, no exponent.
    const numbers = text.match(/-?\d+(\.\d+)?([eE][-+]?\d+)?/g) ?? [];
    for (const number of numbers) {
      assert.match(number, /^-?\d+$/, `${relative} carries a number that is not an integer`);
    }
  }
});

test('the content directory holds only what the manifest names', () => {
  const chapters = fs.readdirSync(path.join(WORKSPACE, CONTENT_DIR, 'chapters'));
  const forms = fs.readdirSync(path.join(WORKSPACE, CONTENT_DIR, 'forms'));
  const { manifest } = contentFiles(WORKSPACE);
  assert.deepEqual(
    chapters.sort(),
    manifest.chapters.map((id) => `${id}.json`).sort(),
    'an unlisted chapter file would be content nothing hashes',
  );
  assert.deepEqual(forms.sort(), manifest.forms.map((id) => `${id}.json`).sort());
});

test('a manifest naming a file that is not there is refused', () => {
  // The eight chapters of the closed set are all authored now, so the name
  // that stands for a missing file is one no chapter file carries.
  const root = scratch(({ read, write }) => {
    write(
      MANIFEST_RELATIVE,
      read(MANIFEST_RELATIVE).replace('"the_pull"', '"the_pull",\n    "the_ninth"'),
    );
  });
  assert.throws(() => contentFiles(root), /the_ninth/);
  // And the real workspace is untouched by any of it.
  assert.doesNotThrow(() => contentFiles(WORKSPACE));
});

test('a manifest naming an id that is not a machine id is refused', () => {
  const root = scratch(({ read, write }) => {
    write(MANIFEST_RELATIVE, read(MANIFEST_RELATIVE).replace('"the_pull"', '"The Pull"'));
  });
  assert.throws(() => contentFiles(root), /machine id/);
});

test('the geometry lint reads the authored content back in whole units', () => {
  const { readings, defects } = geometry(WORKSPACE);
  assert.deepEqual(defects, [], 'the authored content passes its own lint');
  const text = readings.join('\n');
  // Positions, bands, and Route spans, all in units rather than raw.
  assert.match(text, /node \d+ port layer \d+ at \(\d+(\.\d+)?, \d+(\.\d+)?\)/);
  assert.match(text, /current \d+ layer \d+ band \d+(\.\d+)? wide, \d+ points, widest gap/);
  assert.match(text, /route \d+ \d+ to \d+ carrying \d+(\.\d+)? a step, \d+(\.\d+)? apart/);
  assert.match(text, /bright/, 'the opening current is marked');
});

test('the geometry lint reports a band narrower than the drawn minimum', () => {
  const relative = path.join(CONTENT_DIR, 'chapters', 'the_pull.json');
  const root = scratch(({ read, write }) => {
    // Four units, half the minimum, raw.
    write(relative, read(relative).replace('"width": 4194304', '"width": 262144'));
  });
  const { defects } = geometry(root);
  // A band that narrow fails twice over — it is under the minimum, and the
  // path it was authored for is now gapped wider than it can cover.
  assert.ok(defects.some((held) => /below the drawn minimum/.test(held)), defects.join('; '));
  assert.equal(MIN_CURRENT_WIDTH_UNITS, 8);
});

test('the geometry lint reports a current gapped wider than its own band', () => {
  const relative = path.join(CONTENT_DIR, 'chapters', 'the_pull.json');
  const root = scratch(({ read, write }) => {
    // The recipient rule measures to the nearest path point, so a path point
    // dragged far from its neighbour leaves drawn band delivering to nothing.
    write(relative, read(relative).replace('{ "x": 65536000, "y": 133169152 }', '{ "x": 95536000, "y": 133169152 }'));
  });
  const { defects } = geometry(root);
  assert.ok(defects.some((held) => /gap against a/.test(held)), defects.join('; '));
});

test('the geometry lint reports a position off the plane', () => {
  const relative = path.join(CONTENT_DIR, 'chapters', 'the_pull.json');
  const root = scratch(({ read, write }) => {
    write(relative, read(relative).replace('"x": 167772160, "y": 118620160', '"x": 999772160, "y": 118620160'));
  });
  const { defects } = geometry(root);
  assert.ok(defects.some((held) => /outside the plane/.test(held)), defects.join('; '));
});
